Update vpc.tf: Error with vpc.tf file
Got an error in line 12-15 due to deprecated in Terraform v0.12 and it’s not available in the current version.
Error: Error in function call
│ 
│   on vpc.tf line 12, in resource "aws_vpc" "demo":
│   12:   tags = map(
│   13:     "Name", "terraform-eks-demo-node",
│   14:     "kubernetes.io/cluster/${var.cluster-name}", "shared",
│   15:   )
│     ├────────────────
│     │ while calling map(vals...)
│     │ var.cluster-name is a string
│ 
│ Call to function "map" failed: the "map" function was
│ deprecated in Terraform v0.12 and is no longer available;
│ use tomap({ ... }) syntax to write a literal map.

Removed the deprecated function.
tags = {
    Name = "terraform-eks-demo"
    "kubernetes.io/cluster/${var.cluster-name}" = "shared"
  }